auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  wal:
    dir: "/tmp/wal"
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: memberlist

schema_config:
  configs:
    - from: 2024-12-15
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    cache_ttl: 24h
  aws:
    s3: s3://corbierevn:18001090@minio:9000/loki
    s3forcepathstyle: true
