version: "3.9"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "10000:10000"
    logging:
      driver: "json-file"
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network
    depends_on:
      - loki
      - mimir

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/etc/loki
    networks:
      - app-network

  mimir:
    image: grafana/mimir:2.8.0
    container_name: mimir
    ports:
      - "9009:9009"
    volumes:
      - ./mimir:/etc/mimir
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=corbierevn
      - MINIO_ROOT_PASSWORD=18001090
    command: server /data
    ports:
      - "9000:9000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
