global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: nodejs
    static_configs:
      - targets: ["node-app:10000"]
  - job_name: loki
    static_configs:
      - targets: ["loki:3100"]
