# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
    steps:
      - uses: actions/checkout@v4
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
          cache: npm
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm test
  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-test-sample:latest.
          docker push ${{ secrets.DOCKER_USERNAME }}/node-test-sample:latest
  
  deploy:
    name: Deploy to Environment
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Pull and Run Docker Container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/node-test-sample:latest
          docker run -d -p 10000:10000 ${{ secrets.DOCKER_USERNAME}}/node-test-sample:latest


